apigateway:
  build: ../api-gateway-service/
  ports:
    - "8080:8080"
  environment:
    BOARD_COMMANDSIDE_SERVICE_URL: http://boardcommandside:8080
    BOARD_QUERYSIDE_SERVICE_URL: http://boardqueryside:8080
    TASK_COMMANDSIDE_SERVICE_URL: http://taskcommandside:8080
    TASK_QUERYSIDE_SERVICE_URL: http://taskqueryside:8080

boardcommandside:
  build: ../board-command-side-service/
  ports:
    - "8081:8080"

taskcommandside:
  build: ../task-command-side-service/
  ports:
    - "8082:8080"

boardqueryside:
  build: ../board-query-side-service/
  ports:
    - "8083:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/kanban

  build: ../task-query-side-service/
  ports:
    - "8084:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/kanban

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"