kanbanservice:
  image: java:openjdk-8u91-jdk
  working_dir: /app
  volumes:
    - ../standalone-service/build/libs:/app
  command: java -jar /app/standalone-service.jar --spring.data.mongodb.uri=mongodb://mongodb:27017/kanban
  ports:
    - "8080:8080"
  links:
    - mongodb
  environment:
      EVENTUATE_API_KEY_ID:
      EVENTUATE_API_KEY_SECRET:

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
